time = 0.02;
print "\033[0;92m______________________________________\n";
print "\033[0;96m";
print "\rloading:";
sleep time;
print "\rloading:■";
sleep time;
print "\rloading:■■";
sleep time;
print "\rloading:■■■";
sleep time;
print "\rloading:■■■■";
sleep time;
print "\rloading:■■■■■";
sleep time;
print "\rloading:■■■■■■";
sleep time;
print "\rloading:■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■■";
sleep time
print "\rloading:■■■■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■■■■■;"
sleep time;
print "\rloading:■■■■■■■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■■■■■■■";
sleep time
print "\rloading:■■■■■■■■■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■■■■■■■■■■;"
sleep time;
print "\rloading:■■■■■■■■■■■■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■■■■■■■■■■■■";
sleep time
print "\rloading:■■■■■■■■■■■■■■■■■■■■■■■";
sleep time;
print "\rloading:■■■■■■■■■■■■■■■■■■■■■■■■"
sleep time;
print "\rloading:■■■■■■■■■■■■■■■■■■■■■■■■■\n";